apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: { { .Values.global.namespace } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage-service-account
      containers:
        - name: backstage
          image: "{{ .Values.backstage.image.repository }}:{{ .Values.backstage.image.tag }}"
          imagePullPolicy: { { .Values.backstage.image.pullPolicy } }
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "postgres.{{ .Values.global.namespace }}.svc.cluster.local"
            - name: COMPANY_NAME
              value: { { .Values.backstage.companyName | quote } }
