apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: { { .Values.global.namespace } }
type: Opaque
data:
  GITHUB_TOKEN: { { .Values.backstage.github.token | b64enc } }
  GITHUB_CLIENT_ID: { { .Values.backstage.github.clientId | b64enc } }
  GITHUB_CLIENT_SECRET: { { .Values.backstage.github.clientSecret | b64enc } }
  AUTH_ORG_APP_ID: { { .Values.backstage.auth.orgAppId | b64enc } }
  AUTH_ORG_CLIENT_ID: { { .Values.backstage.auth.orgClientId | b64enc } }
  AUTH_ORG_CLIENT_SECRET:
    { { .Values.backstage.auth.orgClientSecret | b64enc } }
  AUTH_ORG_WEBHOOK_SECRET:
    { { .Values.backstage.auth.orgWebhookSecret | b64enc } }
  AUTH_ORG1_PRIVATE_KEY: { { .Values.backstage.auth.orgPrivateKey | b64enc } }
