apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  namespace: { { .Values.global.namespace } }
  labels:
    type: local
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  storageClassName: { { .Values.postgres.storage.className } }
  capacity:
    storage: { { .Values.postgres.storage.size } }
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: { { .Values.postgres.storage.hostPath } }
