apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: { { .Values.global.namespace } }
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-4"
spec:
  storageClassName: { { .Values.postgres.storage.className } }
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: { { .Values.postgres.storage.size } }
