apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: { { .Values.global.namespace } }
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-3"
type: Opaque
data:
  POSTGRES_USER: { { .Values.postgres.secret.user | b64enc } }
  POSTGRES_PASSWORD: { { .Values.postgres.secret.password | b64enc } }
